### PR TITLE
Ar6 test: add test for preliminary ar6 naming and variables

### PR DESCRIPTION
**Pull request by jkikstra**
* data used:
  - model: ssp1-19-message data
  - history:  RCMIP MAGICC data (**N.B.** except for HFC, CF4, and C2F6: those take model data as historical data proxy for now, as I did not find clearly mappable RCMIP data for this)

* **test_ar6.xlsx** is only a placeholder file for now, but needs to be filled with actual test data to pass the test.

* in RunControl: `global_harmonization_only: true`

### CODE REVIEW

**Comment by gidden** [comment]
@jkikstra I will change the base for this PR to `master` now after having merged #15

**Comment by gidden** [comment]
Gah, ok, because I squashed and merged #15, this becomes harder. Apologies. Let's just keep this here for now.

**Comment by gidden** [comment]
@jkikstra I rebased this onto current master so we only see the commits related to this PR

**Comment by gidden** [comment]
Hey @jkikstra is this still needed? My assumption is no and that all cases are covered under #18. If that is correct, please feel free to close! Thanks!

**Comment by jkikstra** [comment]
@gidden I've taken the test files from here and committed them to #18. Therefore I'll close this now.

**Pull request closed without merging**
