### PR TITLE
Workflow

### PR DESCRIPTION
**Pull request by gidden**
Includes #58 and #59 and #60

### CODE REVIEW

**Comment by gidden** [comment]
@coroa - failures here now are in harmonization tests, could you take a look when you have time?

**Comment by gidden** [comment]
cc @coroa on [8f434ed](https://github.com/iiasa/aneris/pull/64/commits/8f434edc3471f72487fe0a463d3b92195d1bfeea)

**Comment by gidden** [comment]
@coroa any idea why black is failing here? Locally I get no required changes..

**Comment by coroa** [comment]
Ah, the new `grid` module we introduce here is effectively not used anymore by `concordia`. We could take a look into concordias [`grid`-module](https://github.com/IAMconsortium/concordia/blob/review/round-1/src/concordia/grid.py) and think whether we want to move some of that into `aneris`.

The main problem is that i was very liberal in the use of `VariableDefinitions` intricacies that i am not sure we want to have directly in here. So maybe easiest to just remove the current module from aneris and then re-add something on a subsequent push.

**Comment by gidden** [comment]
Lack of tests is blocking this merge for now

**Pull request merged**
