### PR TITLE
Update README.rst and xlrd deps

### PR DESCRIPTION
**Pull request by gidden**

### CODE REVIEW

**Comment by gidden** [comment]
Hi @khaeru or @danielhuppmann I apparently no longer have write access here. Could one of you please merge or regrant access?

**Comment by danielhuppmann** [comment]
made you an admin of the repo, @gidden

**Comment by khaeru** [comment]
> made you an admin of the repo, @gidden

…beating me by seconds! 💨 😮

**Review by danielhuppmann — APPROVED** [review]
lgtm, thanks @gidden

**Comment by gidden** [comment]
Thanks both!

**Pull request merged**
