### PR TITLE
Update to pandas > 1.1

### PR DESCRIPTION
**Pull request by znicholls**

### CODE REVIEW

**Comment by znicholls** [comment]
@gidden can you take a look at this please? Not sure how to get the CI to trigger on PR...

**Comment by gidden** [comment]
Hi @znicholls - all looks good except for the change to the value of `sumall` which I do not see a test update or change for.

RE the CI issue, I suspect this is due to the shift from `travis.org` to `travis-ci.com`. I no longer have permissions to update this on IIASA repos, so @khaeru or @danielhuppmann would need to turn the CI back on.

A better option would probably be to migrate this to github actions instead of travis to keep it consistent with other repos.

**Comment by gidden** [comment]
Regarding migration to actions, maybe @jkikstra or @byersiiasa could give it a spin if that is desired

**Comment by byersiiasa** [comment]
I see the actions tab and marketplace but not sure what to select? lmk i can try it out

**Comment by znicholls** [comment]
> all looks good except for the change to the value of `sumall` which I do not see a test update or change for

I didn't actually want to include that, but without it the tests fail. I have no idea why...

**Comment by znicholls** [comment]
I've had a go at setting up github actions, you can see them running here https://github.com/znicholls/aneris/actions

**Comment by danielhuppmann** [comment]
So my understanding is that GitHub Actions will only run workflow recipes after they are merged. So if you want to have them run on the pandas>1.1 PR, the easiest would be to first make a PR with just the workflow recipe, review and merge that, then create a second PR that has (only) the refactoring...

**Comment by znicholls** [comment]
> So my understanding is that GitHub Actions will only run workflow recipes after they are merged

You can get them to run in the fork, see e.g. https://github.com/znicholls/aneris/actions

**Comment by znicholls** [comment]
> the easiest would be to first make a PR with just the workflow recipe, review and merge that, then create a second PR that has (only) the refactoring

I'm also happy to do this two step process if you/@gidden would prefer

**Comment by khaeru** [comment]
> I'm also happy to do this two step process if you/@gidden would prefer

This would seem to be the only way to ensure that the substantive changes to the code in this PR will pass the workflow.

**Comment by znicholls** [comment]
Will do tomorrow

**Comment by gidden** [comment]
@znicholls sorry for clobbering this PR, but hopefully it will save you some time.

I added the current non-regression based testing as github workflows, working on your start here. I had to remove windows and py3.9 because of some depedency snafus, which I suspect will be overcome with the pandas update. I also had to freeze numpy - same reason, same hopefully resolution. 

- #36 implements the workflows as described, and outlines next steps
- #37 provides a template for adding back regression tests (will need assistance from IIASA colleagues, please and thank you!)

**Comment by gidden** [comment]
Ok, @znicholls - have merged the final PR into `master` - this should be able to be rebuilt on top of that and all tests with regressions will run.

**Comment by znicholls** [comment]
Alright I think this is good to go @gidden. I've added the windows tests back in too and added some extra pandas ones. I don't understand the `sumall` change, but as I said things fail without it.

**Comment by znicholls** [comment]
@jkikstra are you able to progress this?

**Comment by gidden** [comment]
Triple checked with #40 - everything passes. Thanks @znicholls !

**Pull request merged**
