### PR TITLE
Add customizable method_choice

### PR DESCRIPTION
**Pull request by coroa**
Allow passing a replacement/amendment for the default method choice
decision tree as an argument to Harmonizer.

Depends on #27 , so for review only look at last commit.

### CODE REVIEW

**Review by gidden — CHANGES_REQUESTED** [review]
Thanks @coroa - I have reviewed and approve of all code changes. One request would be a test, which could be added to `test_default_decision_tree.py` utilizing the new kwarg. If I missed it, feel free to point me to it.

**Comment by coroa** [comment]
> Thanks @coroa - I have reviewed and approve of all code changes. One request would be a test, which could be added to `test_default_decision_tree.py` utilizing the new kwarg. If I missed it, feel free to point me to it.

Added

**Comment by gidden** [comment]
Great, thanks!

**Review by gidden — APPROVED** [review]
lgtm

**Pull request merged**
