### PR TITLE
Add black

### PR DESCRIPTION
**Pull request by lewisjared**
Use black to consistently format code. It could also be worth using a pre-commit hook so that this is handled automatically on commit.

Also adds black checks to stickler

### CODE REVIEW

**Comment by gidden** [comment]
Thanks @lewisjared - I will acquiesce to turning `aneris` to the dark side

**Comment by lewisjared** [comment]
I'll figure out what's happening tomorrow

**Comment by lewisjared** [comment]
Ok I think I fixed the problem. There was a usage of `pd_read` in the `aneris.utils`, but it wasn't imported because it exploded due to a cyclic dependency. `aneris.utils` imported `aneris._io.pd_read` and `aneris._io` imported functions from `aneris.utils`.  To resolve that I moved `pd_read` and `pd_write` to `aneris.utils` which breaks that cycle.

This isn't a breaking change as `pd_read` is exposed via `aneris.pd_read` already.

The other option is to late import the module, but that just hides the fact that there is a cycle.

**Comment by gidden** [comment]
Sounds good! Rerunning CI now.

**Comment by gidden** [comment]
Thanks @lewisjared !

**Pull request merged**
